services:
  budgetserver:
    image: ${DOCKER_REGISTRY-}budgetserver
    build:
      context: .
      dockerfile: BudgetServer/Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
